//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagementSystemERDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailType
    {
        public EmailType()
        {
            this.Emails = new HashSet<Email>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<Email> Emails { get; set; }
    }
}
