//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagementSystemERDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupation
    {
        public Occupation()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public int OccupationType_Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual OccupationType OccupationType { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
